### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DosWorld** [ZaneDubya/Small-C#12]
Could you plase specify license for your work. I want fork it but cant.

**Comment by ZaneDubya** [comment]
Hi DosWorld - I am releasing the ylink software to the public domain, just as J. E. Hendrix Jr. released the other source code in the repo. I added "license.txt" in the repo root to make this clear.

**Comment by ZaneDubya** [comment]
By the way, I'd be excited to hear about what you're working on!

**Comment by DosWorld** [comment]
1. I am write basic-compiler (it is near to be done). Formaly basic to assembler translator.
2. Have idea make mix between my basic and Small C (call C-functions from my basic) - this is a reason why I came (You make interesting fix for small c - increase function name length)

PS: I think, You can check it - https://github.com/DosWorld/smallmake

**Comment by ZaneDubya** [comment]
That sounds like a fun project. With SmallA and YLink, you would have all the programs you need to translate input through your compiler to a small memory model exe.

**Comment by DosWorld** [comment]
> That sounds like a fun project.

Yes and no. I am to try create serious compiler. For example, now i have text editor wroten in my basic (print/locate works with nansi.sys, speed is good, 300-350 lines in basic) and disassebler for 8080. With time, I want to troll community by software in basic (like text editr, spreadsheet, games). May be, with time, i hope add register optimization for code generator.

In any case, first what i want to do - improve clib speed. At first, i am create makefile for clib - it allow dont build full lib, it allow recompile changed files only. I start rewrite key functions in assembler (like a strcpy, strcmp). Next problem - i have no free lib tool. (i am use tlib from borland, but its bad)...
