### ISSUE TITLE
ASM fails with labels in jumps

### ISSUE THREAD

**Issue by DosWorld** [ZaneDubya/Small-C#13]
Code is pass compilation with original version C+ASM (by Hendrix) but fails on new. Check code in attachements.

REVERSE.ASM - fails assembler on jumps (all jump to labels like rev*). I am try change label names - it dont help.

CLIB.H+REVERSE.C - source

[REVERSE.ZIP](https://github.com/ZaneDubya/Small-C/files/3342203/REVERSE.ZIP)

**Comment by ZaneDubya** [comment]
I’m not supporting this software.
